### ISSUE TITLE
Problema migrate comuni

### ISSUE THREAD

**Issue by rossellamascia** [Bisark/laravel-province-comuni#1]
Le province funzionano perfettamente ma i comuni no.
Ti lascio l'errore del teriminale
<img width="1180" alt="Schermata 2020-12-19 alle 21 22 25" src="https://user-images.githubusercontent.com/42215075/102698791-55d08080-4240-11eb-95f0-fda880453566.png">
<img width="993" alt="Schermata 2020-12-19 alle 21 23 11" src="https://user-images.githubusercontent.com/42215075/102698800-6b45aa80-4240-11eb-85ed-48d431c33b38.png">

**Comment by bisark** [comment]
Grazie per la segnalazione, ora dovrebbe essere risolto.
