### ISSUE TITLE
Chiave duplicata

### ISSUE THREAD

**Issue by diegodeluca** [Bisark/laravel-province-comuni#2]
Non so se sono il primo a cui capita ma quando lancio la migrazione ricevo un errore di chiave duplicata col codice della provincia.

```sql
PDOException::("SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '0' for key 'province_codice_unique'")
```

**Comment by bisark** [comment]
Grazie mille per la segnalazione, problema risolto.
